#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e
source /home/miniconda3/etc/profile.d/conda.sh

# Step 1: Activate SRAtools environment
conda activate SRAtools

# Step 2: Convert .sra files to FASTQ with fasterq-dump and compress with pigz
for sra_file in *.sra; do
    echo "Processing $sra_file..."
    base_name=$(basename "$sra_file" ".sra")
    
    if fasterq-dump --split-files --outdir ./ --threads 4 "$sra_file"; then
        pigz "${base_name}_1.fastq" "${base_name}_2.fastq" 
        echo "Successfully processed $sra_file"
    else
        echo "Failed to process $sra_file"
        continue
    fi
done

# Step 3: Deactivate SRAtools environment
conda deactivate

# Step 4: Activate seqtk environment
conda activate seqtk

# Step 5: Subsample FASTQ files using seqtk and compress the results with pigz
for fastq_file in *_1.fastq.gz; do
    base_name=$(basename "$fastq_file" "_1.fastq.gz")

    if [[ -f "${base_name}_2.fastq.gz" ]]; then
        if seqtk sample -s410 "${base_name}_1.fastq.gz" 20000000 > "${base_name}_1_20M.fastq" && \
           seqtk sample -s410 "${base_name}_2.fastq.gz" 20000000 > "${base_name}_2_20M.fastq"; then
            echo "Subsampling completed for $base_name"
        else
            echo "Failed to subsample $base_name"
            continue
        fi
    else
        echo "Missing paired file for $base_name. Skipping subsampling."
    fi
done

# Step 6: Compress subsampled FASTQ files with pigz
pigz -p 6 *_20M.fastq

# Step 7: Deactivate seqtk environment
conda deactivate

# Step 8: Activate fastqc environment
conda activate fastqc

# Step 9: Run fastqc on subsampled FASTQ files
for fastq_file in *_1_20M.fastq.gz; do
    base_name=$(basename "$fastq_file" "_1_20M.fastq.gz")

    if [[ -f "${base_name}_2_20M.fastq.gz" ]]; then
        fastqc "${base_name}_1_20M.fastq.gz" "${base_name}_2_20M.fastq.gz"  # No output directory specified
        echo "FastQC processing completed for $base_name"
    else
        echo "Missing paired file for FastQC processing for $base_name. Skipping."
    fi
done

# Step 10: Deactivate fastqc environment
conda deactivate

echo "All tasks completed successfully!"

# Step 11: Activate Mitoz
conda activate mitoz

# Step 12: Set up MitoZ
 circos --modules
mitoz
  mitoz-tools
    python3
      from ete3 import NCBITaxa
ncbi = NCBITaxa()
  from ete3 import NCBITaxa
      a = NCBITaxa()
      a.get_name_translator(["Arthropoda"])
        {'Arthropoda': [6656]}

# Step 13: Run MitoZ
mitoz all \
--outprefix ascaris_mito_20M \
--thread_number 4 \
--clade Nematoda \
--genetic_code 5 \
--species_name "Ascaris" \
--fq1 *R1_20M.fastq.gz \
--fq2 *R2_20M.fastq.gz \
--fastq_read_length 151 \
--data_size_for_mt_assembly 3,0 \
--assembler megahit \
--kmers_megahit 31 39 51 71 99 \
--memory 32 \
--requiring_taxa Nematoda


